function [options,results,zHR] = find_threshPC(data_to_fit,options)
%[options,results] = find_threshPC(data_to_fit,options)
%
%This function determines the percent correct value at which d' ==
%threshold. We use this value as the value at which psignifit 4 should
%calculate threshold and CIs.
%
%Input variables:
%   data_to_fit: M x 3 matrix arranged as [stimulus value, n_yes, n_trials]
%                        (stimulus values are already in dB re: 100% depth)
%
%   options: structure given by setOptions function for fitting
%
%Output variables:
%   options: updated options structure with percent correct value
%   results: structure generated by psignifit 4
%
%Written by ML Caras Dec 5 2016


%edited by cgs 6/2/21
n_HR = data_to_fit(1,2);
n_goTrial = data_to_fit(1,3);
n_fa = data_to_fit(end,2);
n_safe = data_to_fit(end,3);

zHR = sqrt(2)*erfinv(2*(n_HR/n_goTrial)-1);
zFA = sqrt(2)*erfinv(2*(n_fa/n_safe)-1);
% zThresh = options.dprimeThresh+zHR;
zThresh = options.dprimeThresh;
options.threshPC = (erf(zThresh/sqrt(2))+1)/2;

%Fit the data
results = psignifit(data_to_fit,options);

%Remove fields that are much too large to be worth saving
results = rmfield(results,'Posterior');
results = rmfield(results,'weight');